build: false

image:
  - Visual Studio 2019
  - macOS
  - Ubuntu1804

platform: x64

for:
-
  matrix:
    only:
      - image: Visual Studio 2019
  build_script:
  - set CL=/MP # parallel build
  - mkdir build && cd build
  - cmake .. -G "Visual Studio 16 2019" -A Win32 -DQTDIR="C:\Qt\5.14.2\msvc2017"
  - cmake --build . --config Release
-
  matrix:
    only:
      - image: macOS
  install:
  - brew update
  - brew install qt5
  build_script:
  - mkdir build && cd build
  - cmake .. -DQTDIR="/usr/local/opt/qt"
  - cmake --build . -- -j4
-
  matrix:
    only:
      - image: Ubuntu1804
  install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.14.2-bionic # 5.14 here because there is no ppa for 5.15 for 18.04
  - sudo apt-get update
  - sudo apt-get install -y qt514-meta-full libgl-dev
  build_script:
  - mkdir build && cd build
  - cmake .. -DQTDIR="/opt/qt514"
  - cmake --build . -- -j4
